### ISSUE TITLE
Implement Cake-Contrib guidelines

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Npm.Module#19]
Reference https://www.nuget.org/packages/CakeContrib.Guidelines/ and follow it's guides.

Also check https://github.com/cake-contrib/Home/blob/master/Guidelines.md for additional requirements. (I.e. multi-targeting to netstandard2.0 and net461)

**Comment by nils-a** [comment]
@AdmiringWorm would it make sense to also add a reference to `Cake.Addin.Analyzer` ?

**Comment by AdmiringWorm** [comment]
@nils-a no, it would not make sense.
The analyzer is purely for addins, and is of no use for modules.
