### ISSUE TITLE
add dependabot-configuration and build in github

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Npm.Module#22]
* Dependencies should be kept up-to-date by adding a `.github/dependabot.yml`
* `Do not build on "Pull request" events` should be set in AppVeyor settings
* GitHub-Actions should be added to have a build on PRs

These changes conform to https://cake-contrib.github.io/Cake.Recipe/docs/upgrading/1.x-to-2.x, sections *Add dependabot config file* and *Add GitHub Actions*.

**Comment by nils-a** [comment]
@gep13 missing to close this issue is
>`Do not build on "Pull request" events` should be set in AppVeyor settings

But I don't have the permissions in AppVeyor. Could you update the settings accordingly and then close this issue?

**Comment by gep13** [comment]
I would, but I would like to see if I can adjust permissions to allow you to do this. Let me try giving you those permissions....

**Comment by nils-a** [comment]
I have updated the settings in AppVeyor, now.
