### ISSUE TITLE
installed tools should be available in the IToolLocator

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Npm.Module#72]
## Current status

When installing some tool locally, it is installed in the `WorkingDirectory`, not in the tools folder.
While this works for most cases the tool is not available as a tool in cake. I.e. it will not be found by the IToolLocator.

Example:
```cakescript
#module nuget://?package=Cake.Npm.Module
#tool npm://?package=yo

Task("Default")
.Does(() => {
   var yo = Context.Tools.Resolve("yo.cmd");
   if(yo == null) {
      yo = Context.Tools.Resolve("yo");
   }
   if(yo == null) {
      Error("Something is very wrong.");
      throw new Exception("yo not found!");
   }
   Information("yo installed at: " + yo.FullPath);
   IEnumerable<string> version;
   StartProcess(
      yo,
      new ProcessSettings {
            Arguments = "--version",
            RedirectStandardOutput = true
      },
      out version);
   Information("yo version: " + version.First());
});

RunTarget("Default");
```

this will not find `yo` as a tool, unless `yo` was installed globally on the system (either by installing it manually or by setting `#tool npm://?package=yo&global`)
Additionally, the `node_modules` folder will "clutter" the `WorkingDirectory`.

## Proposal

I propose adding a new flag `caketool` (to not break current API) which will install the tool unter the `tools` folder. This will keep the `WorkingDirectory` "clean" and make all tools available for usage as tools in Cake. I.e. after implementing that, setting `#tool npm://?package=yo&caketool` will make above example work.

**Comment by nils-a** [comment]
@agc93 do you have thoughts on this?

**Comment by agc93** [comment]
Huh, that's a good point. That flag seems like a good method to me and would make that "method" pretty self-explanatory in use so seems like a good idea!

To be honest, looking back I'm not sure why I didn't do it that way from the start 😆
